### GET Bearer Token
POST https://38d9c0aatrial.authentication.us10.hana.ondemand.com/oauth/token?grant_type=client_credentials&response_type=token
Authorization: Basic sb-38d9c0aatrial-dev-sample!t170769 k7eix77fG56GZKiHCtFJgHsT/CU=

> {% client.global.set("bearer_token", response.body.access_token); %}

### CALL SUBMIT JOB API
GET http://localhost:8080/sample-java/hello
Authorization: Bearer {{bearer_token}}
Content-Type: application/json


